Categories:
  - Inventory
License: Apache-2.0
SourceCode: https://github.com/joman2/open-pharma-stock
IssueTracker: https://github.com/joman2/open-pharma-stock/issues

Name: open-pharma-stock

RepoType: git
Repo: https://github.com/joman2/open-pharma-stock.git

Builds:
  - versionName: 0.2.2
    versionCode: 4
    commit: v0.2.2
    output: build/app/outputs/flutter-apk/app-release.apk
    srclibs:
      - flutter@3.38.3
    prebuild:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter pub get --enforce-lockfile
    scandelete:
      - .pub-cache
    build:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter build apk --release --no-pub

AutoUpdateMode: Version
UpdateCheckMode: Tags ^v[0-9]+\.[0-9]+\.[0-9]+$
UpdateCheckData: pubspec.yaml|version:\s.+\+(\d+)|.|version:\s(.+)\+
CurrentVersion: 0.2.2
CurrentVersionCode: 4
